base:
  build: .
  ports:
    - "3025:3025"
  container_name: fw-contextual-layer
  environment:
    PORT: 3025
    NODE_PATH: app/src
mongo:
  image: mongo
  container_name: fw-contextual-layer-mongo
  command: --smallfiles
  ports:
    - "27017"
  volumes:
    - $HOME/docker/data/fw-contextual-layer:/data/db
  restart: always

