prod:
  image: vizzuality/fw-contextual-layer:1.0.0${STAGING}
  ports:
    - "3025"
  env_file:
    - prod.env
  command: start
  dns: ${DNS_SERVER}
  restart: always
  log_driver: "syslog"
  log_opt:
      syslog-address: ${SYSLOG_ADDRESS}
      tag: fw-contextual-layer${STAGING}
