apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: fw
  labels:
    name: fw-contextual-layers
  name: fw-contextual-layers
spec:
  revisionHistoryLimit: 0
  template:
    metadata:
      annotations:
        chaos.alpha.kubernetes.io/enabled: "true"
      labels:
        name: fw-contextual-layers
    spec:
      containers:
      - name: fw-contextual-layers
        image: vizzuality/fw-contextual-layers
        imagePullPolicy: Always
        resources:
          requests:
            memory: "0Mi"
            cpu: "0m"
        args:
          - start
        env:
          - name: PORT
            value: "3025"
          - name: NODE_ENV
            value: staging
          - name: NODE_PATH
            value: app/src
          - name: LOCAL_URL
            value: http://fw-contextual-layers.fw.svc.cluster.local:3025
          - name: MONGO_URI
            valueFrom:
                secretKeyRef:
                  name: dbsecrets
                  key: CONTEXTUAL_LAYERS_MONGO_URI
          - name: CT_URL
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: CT_URL
          - name: CT_TOKEN
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: CT_TOKEN
          - name: CT_REGISTER_MODE
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: CT_REGISTER_MODE
          - name: API_VERSION
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: API_VERSION

        ports:
          - containerPort: 3025

      restartPolicy: Always
